### ISSUE TITLE
Mascot ja

### ISSUE THREAD

**Issue by KonLew** [TonNattapon/risky#10]
อันนี้แบบ prototype นะ
-เปลี่ยนได้หมดทุกอย่างเลย 
-รอทำ animation

**Comment by KonLew** [comment]
![image](https://user-images.githubusercontent.com/110968155/220576420-bbc9c466-758a-40e6-ab87-202eba9f304e.jpeg)

**Comment by r1chwo0n** [comment]
สุดเท่😎🤟🏾

**Comment by KonLew** [comment]
![cat1 gif](https://user-images.githubusercontent.com/110968155/222438804-cb83cbba-0695-483f-9dfd-b82d8b269533.gif)
[cat1.zip](https://github.com/TonNattapon/risky/files/10871691/cat1.zip)

**Comment by KonLew** [comment]
![cat2gif](https://user-images.githubusercontent.com/110968155/222509990-0ce97afa-cb90-4619-8557-4ecd60934676.gif)
[cat2.zip](https://github.com/TonNattapon/risky/files/10874206/cat2.zip)

**Comment by KonLew** [comment]
ดูทรงเหมือนสีจะเพี้ยน แต่เปิดในไฟล์คือโอเค ให้ใช้ไฟล์แตกเอานะ

**Comment by KonLew** [comment]
![cat3gif](https://user-images.githubusercontent.com/110968155/222775337-9a53b5e3-303a-4fda-aaba-f107f82c8d44.gif)
[cat3.zip](https://github.com/TonNattapon/risky/files/10884203/cat3.zip)

**Comment by r1chwo0n** [comment]
เท่สุปๆ พี่หมิวเก่งมาก👍🏻
