### ISSUE TITLE
สร้างถาดวางแผ่นป้าย

### ISSUE THREAD

**Issue by Piicharpa** [TonNattapon/risky#12]

**Comment by r1chwo0n** [comment]
แบมบี้ไอขอโค้ดที่ยูวางไว้หน่อย🙏 อยากจะเอามาลองดู

**Comment by bbambiiisadeer** [comment]
ส่งไปแล้วในดิส

**Comment by bbambiiisadeer** [comment]
void tray(int a){
        list<int> mycard;
        list<int>::iterator loc;
    if(mycard.size() <= 7){
        loc = find(mycard.begin(), mycard.end(), a);
        if(*loc != 0) mycard.insert(loc, a);
        else mycard.push_back(a);
    }

}

**Comment by bbambiiisadeer** [comment]
-ทดลองโค้ดเรียง 3 ในถาดแล้วหายได้แล้ว แต่ยังเป็นแค่ค่าตัวแปรจำนวนเต็มธรรมดา
