### ISSUE TITLE
BGหน้าต่างเกม

### ISSUE THREAD

**Issue by r1chwo0n** [TonNattapon/risky#2]

**Comment by r1chwo0n** [comment]
สีไหนดีคับ🥶 เสนอสีมาได้เลยคับ เด่วจะทำลายไปพลางๆคับ
![IMG_7772](https://user-images.githubusercontent.com/110924108/222179156-3af0f37a-3134-4465-9316-f7a38e126188.jpeg)

**Comment by poonbcw** [comment]
ชอบสีม่วงงงงงงง

**Comment by r1chwo0n** [comment]
![IMG_7781](https://user-images.githubusercontent.com/110924108/222322655-1becc102-7ea5-48a4-ad7b-0afbc44a056e.jpeg)

**Comment by r1chwo0n** [comment]
![IMG_7786](https://user-images.githubusercontent.com/110924108/222323935-dbb2d914-8548-4934-bd19-a0eaabdbf4e6.jpeg)

**Comment by r1chwo0n** [comment]
![IMG_7787](https://user-images.githubusercontent.com/110924108/222324883-8d40b0ed-5c42-4210-9bec-2da3e57ee970.jpeg)

**Comment by r1chwo0n** [comment]
![IMG_7789](https://user-images.githubusercontent.com/110924108/222325359-aedc8cbe-4fac-413d-acca-5677a74b857f.jpeg)
![IMG_7788](https://user-images.githubusercontent.com/110924108/222325437-ec9fdd86-3daa-45b4-940a-402836df8927.jpeg)
![IMG_7790](https://user-images.githubusercontent.com/110924108/222325480-dff2fe8f-24d1-423f-8333-a0ac3959998e.jpeg)

**Comment by r1chwo0n** [comment]
โหวตหน่อยคับ

**Comment by Piicharpa** [comment]
โหวตสีเขียวว

**Comment by KonLew** [comment]
แอบชอบม่วง

**Comment by bbambiiisadeer** [comment]
ม่วงtoo

**Comment by TonNattapon** [comment]
ม่วง+1

**Comment by r1chwo0n** [comment]
ปิดโหวตที่สีม่วงนะข่าบ
