### ISSUE TITLE
การนำไพ่ไปไว้ในถาด

### ISSUE THREAD

**Issue by Piicharpa** [TonNattapon/risky#21]

**Comment by Piicharpa** [comment]
ต่อไปมีความคืบหน้าอะไรลงในนี้หน่าหน่องปุน

อันนี้คือกูลองเขียนโค้ดตามที่มึงบอกดูไม่รู้ว่าเข้าใจตรงกันมั้ย เดะมึงลองดูก่อน

![image](https://user-images.githubusercontent.com/110968305/224563876-8ce75feb-e637-4631-b317-770e42217f87.png)

**Comment by Piicharpa** [comment]
ปุนพอดี code เค้ามันหาย ขอ codeล่าสุดที่เราแก้กันหน่อย

**Comment by poonbcw** [comment]
[testtt.txt](https://github.com/TonNattapon/risky/files/10969256/testtt.txt)
เอาเป็นไฟล์ text ไปก่อนนะ

**Comment by Piicharpa** [comment]
ขอบคุณจ้าา

**Comment by Piicharpa** [comment]
ปุนช่วยดู code ให้หน่อยย
[ne.co.txt](https://github.com/TonNattapon/risky/files/10970191/ne.co.txt)
