### ISSUE TITLE
pieces design

### ISSUE THREAD

**Issue by r1chwo0n** [TonNattapon/risky#3]
ออกแบบแผ่นป้ายจับคู่

**Comment by r1chwo0n** [comment]
Day 1 ขอคอมเม้นหน่อยคับ ออกแบบพวกอุปกรณ์+การ์ตูนสัตว์ได้มั้ย ส่วนสีออกนอกธีมหน่อยได้มั้ย ส่วนอย่างอื่นยังคงคุมสีอยู่ เช่น พื้นหลัง ภาพรวม เป็นต้น ถ้าทำแบบนี้จะได้มั้ย
![IMG_7546](https://user-images.githubusercontent.com/110924108/220170607-c6cb9c6a-c220-4c31-ba30-b5567a88a084.png)
![IMG_7549](https://user-images.githubusercontent.com/110924108/220171069-8bba4109-d844-43b4-8471-0d1126cdd85e.png)
![IMG_7551](https://user-images.githubusercontent.com/110924108/220171103-505e15aa-c6b6-49a9-9f44-f8730f96ce4d.png)
![IMG_7555](https://user-images.githubusercontent.com/110924108/220171141-1561109c-c4ce-4e90-b0e5-cede2c0d52d7.png)
![IMG_7558](https://user-images.githubusercontent.com/110924108/220171182-f883531f-e06e-4404-9a62-4705a474552c.png)

**Comment by KonLew** [comment]
คิดว่าน่ารักเลยเป็นสัตว์ก็ดูน่าเล่นไปอีกแบบอะ 
สีหลุดตีมได้ไม่เป็นไรหรอก ตีมเราเอามาคลุมอินเตอเฟดพอละ เยี่ยมๆ👍🏻✨

**Comment by TonNattapon** [comment]
น่ารักยู้ แต่ต้องดูสีให้เข้ากับส่วนประกอบอื่นๆ ของเกมด้วย

**Comment by r1chwo0n** [comment]
Day2 เกือบจะหมดมุกแล้วอ่ะ สีเดี๋ยวจะมาปรับอีกทีคับถ้าอะไรใดๆเข้าที่ (ขอลองเอามาใส่พื้นหลังดูก่อนน้า) อีก 5 รูปคาดว่าจะเอา vs code GitHub c++ 404not found hard disk 
![IMG_7572](https://user-images.githubusercontent.com/110924108/220413938-e93ff5dc-27e8-455f-99cb-ce55e07357b7.png)
![IMG_7576](https://user-images.githubusercontent.com/110924108/220413984-9e537ad5-79ef-4e6b-892d-841b18916130.png)
![IMG_7580](https://user-images.githubusercontent.com/110924108/220414018-ccbe1a01-a78a-4d1a-ac5c-d2f7e5e619e5.png)
![IMG_7586](https://user-images.githubusercontent.com/110924108/220414046-1fa359d5-7ebc-4634-8ae2-d6c645365fe8.png)
![IMG_7588](https://user-images.githubusercontent.com/110924108/220414088-7992c71f-5d87-4e54-9271-e88442c0e96b.png)

**Comment by TonNattapon** [comment]
ขนาดของชิ้นขอเป็น W 48*H 66 px นะ

**Comment by r1chwo0n** [comment]
Day3 เสร็จครบทุกตัวแร้ววว ขนาดของชิ้นรับทราบฮะ🫡 พนคาดว่าคงเสร็จของส่วนนี้คับ
![IMG_7601](https://user-images.githubusercontent.com/110924108/220694370-52c1720a-31b0-4004-bd51-04dba02024e2.png)
![IMG_7603](https://user-images.githubusercontent.com/110924108/220694457-2f982d66-f879-4b0a-8ace-5dd37c2114ff.png)
![IMG_7608](https://user-images.githubusercontent.com/110924108/220694618-8ea00880-efe5-4bfb-80fc-89a215f31807.png)
![IMG_7610](https://user-images.githubusercontent.com/110924108/220694716-54c0981b-86f6-4295-b8a6-56b452dcbb7c.png)
![IMG_7612](https://user-images.githubusercontent.com/110924108/220694860-8364af81-8267-436a-bae2-b932644fffbf.png)

**Comment by Piicharpa** [comment]
น่ารักเวอร์

**Comment by r1chwo0n** [comment]
มันเล็กมากอ่ะแล้วมันแตกหมดเลย พอจะมีวิธีมั้ยที่ยังไม่ต้องปรับสเกลรูปตามที่ยูส่งมา🥲 หรือไม่ว่าจะปรับขนาดรูปก่อนหรือหลังภาพก็แตกอยู่ดีเพราะขนาดมันเล็ก

**Comment by r1chwo0n** [comment]
หรือต้องวาดใหม่ด้วยสเกลเท่านี้T-T

**Comment by Piicharpa** [comment]
วุ้นปรับภาพในไหนอะ คือเค้าไปอ่านมาเขาบอกให้ลองปรับภาพใน photoshop ดูอะ

**Comment by r1chwo0n** [comment]
เค้าปรับใน procreate อ่ะ เหนือส่งลิ้งก์มาให้หน่อยได้มั้ย

**Comment by r1chwo0n** [comment]
ลองเปลี่ยนรูปเป็นแบบpixel เส้ดล้ะฮะ ไม่ค่อยถนัดแนวนี่เท่าไหร่🥶 เพิ่มตรงไหนบอกได้เลยนะ
![IMG_7718](https://user-images.githubusercontent.com/110924108/221508781-39fb9436-e41d-40fa-8bd7-c151e8d49bf9.png)
![IMG_7719](https://user-images.githubusercontent.com/110924108/221508820-295804b2-1f24-4298-8b9e-1e5bd33f456c.png)
![IMG_7720](https://user-images.githubusercontent.com/110924108/221509003-5eabb8ad-7ae2-4b4f-9293-4b1d5be84a96.png)
![IMG_7721](https://user-images.githubusercontent.com/110924108/221509087-cd12db2f-40b5-4d83-a700-848a31ee67a5.png)
![IMG_7722](https://user-images.githubusercontent.com/110924108/221509114-a9900315-7cc6-4ad6-9594-e6bf8f850cad.png)
![IMG_7723](https://user-images.githubusercontent.com/110924108/221509184-11ad5ef0-33bf-40fa-ad66-dce65ab2c700.png)
![IMG_7724](https://user-images.githubusercontent.com/110924108/221509211-8a4cd4fc-fb08-43ea-a89e-453226335d4a.png)
![IMG_7725](https://user-images.githubusercontent.com/110924108/221509262-f825e8ef-c946-433f-9783-43846e6d19ef.png)
![IMG_7726](https://user-images.githubusercontent.com/110924108/221509317-98978462-b7ec-4996-9d9b-ea0fbd0ba967.png)
![IMG_7727](https://user-images.githubusercontent.com/110924108/221509377-a91d23cb-b9cd-4a88-b37b-52c6638f343c.png)
![IMG_7728](https://user-images.githubusercontent.com/110924108/221509419-c0fb7c96-925f-4c3d-a1d6-8112e817e919.png)
![IMG_7729](https://user-images.githubusercontent.com/110924108/221509450-f6ff036b-1079-4fa7-ae33-1c561780ccf6.png)
![IMG_7730](https://user-images.githubusercontent.com/110924108/221509499-fac87d8f-53f4-4a0b-b6c0-0251e90ae210.png)
![IMG_7731](https://user-images.githubusercontent.com/110924108/221509531-ed93f3c6-2d96-4b3a-abf9-97d372ceb80b.png)
![IMG_7732](https://user-images.githubusercontent.com/110924108/221509544-9ade4e10-caef-4369-824c-4a064e1474e3.png)

**Comment by r1chwo0n** [comment]
ปัญหา: มันดูเหลื่อมๆไม่ค่อยสวย
วิธีแก้: เลยลองทำตามต้นแบบคือทำให้มันมีมิติ นี่อัพลงไดรฟ์ไว้ ลองเอาไปลงกับโค้ดให้หน่อยคับว่าได้มั้ย
