### ISSUE TITLE
Game over

### ISSUE THREAD

**Issue by r1chwo0n** [TonNattapon/risky#5]

**Comment by KonLew** [comment]
background eiei
![cat meme](https://user-images.githubusercontent.com/110968155/223672150-ff6ec1cb-b26d-4d4d-8f09-d77f4a4e3d67.png)

**Comment by KonLew** [comment]
game over
![game over](https://user-images.githubusercontent.com/110968155/223672275-d140cadb-8ff0-4fc5-89bf-1b9581600e7d.png)

**Comment by KonLew** [comment]
restart
![restart](https://user-images.githubusercontent.com/110968155/223672353-c6ed7a19-0ca0-405a-b618-abe85910709c.png)
