### ISSUE TITLE
Start page

### ISSUE THREAD

**Issue by r1chwo0n** [TonNattapon/risky#6]
Home page

**Comment by KonLew** [comment]
858*570
![223152014-3e723aed-cc7f-43de-8ff9-d75f2a858697](https://user-images.githubusercontent.com/110968155/223195246-27dc8847-9d05-42a9-b41c-ce076906eeca.jpeg)

**Comment by KonLew** [comment]
start
![start](https://user-images.githubusercontent.com/110968155/223195328-3a341c1b-637a-4fbe-a37e-67ec9c36603f.png)

**Comment by KonLew** [comment]
setting
![setting](https://user-images.githubusercontent.com/110968155/223195396-ba3f3a3a-494f-4059-b9d2-a65ca4c980ab.png)

**Comment by KonLew** [comment]
ปุ่มต่างๆ
https://itch.io/game-assets/free/tag-buttons

**Comment by KonLew** [comment]
how to play
![how to play](https://user-images.githubusercontent.com/110968155/223659340-a89bc5fa-af06-41ef-98f7-2f9b8c24294f.png)
